# Generated by Django 4.0.3 on 2025-12-27 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان اعلان')),
                ('message', models.TextField(verbose_name='متن اعلان')),
                ('notification_type', models.CharField(choices=[('order', 'سفارش'), ('system', 'سیستم'), ('promotion', 'تخفیف'), ('other', 'سایر')], default='system', max_length=20, verbose_name='نوع اعلان')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('icon', models.CharField(blank=True, help_text='نام کلاس آیکون (اختیاری)', max_length=50, null=True, verbose_name='آیکون')),
                ('orderf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='order.order', verbose_name='سفارش مرتبط')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'اعلان',
                'verbose_name_plural': 'اعلان\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
