# Generated by Django 4.0.3 on 2025-12-27 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0009_alter_copon_enddate_alter_copon_startdate_and_more'),
        ('dashboard', '0002_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='orderf',
            new_name='order',
        ),
        migrations.AddField(
            model_name='notification',
            name='copon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='discount.copon', verbose_name='کوپن مرتبط'),
        ),
    ]
