# Generated by Django 4.0.3 on 2025-12-09 09:08

import apps.product.models.brand
import apps.product.models.category
import apps.product.models.gallery
import apps.product.models.product
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='اسلاگ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('data_type', models.CharField(choices=[('text', 'متن'), ('integer', 'عدد صحیح'), ('decimal', 'عدد اعشاری'), ('boolean', 'صحیح/غلط'), ('date', 'تاریخ'), ('datetime', 'تاریخ و زمان'), ('select', 'انتخاب از لیست'), ('multi_select', 'انتخاب چندتایی'), ('color', 'رنگ')], default='text', max_length=20, verbose_name='نوع داده')),
                ('options', models.TextField(blank=True, verbose_name='گزینه\u200cها (هر خط یک گزینه)')),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='حداقل مقدار')),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='حداکثر مقدار')),
                ('max_length', models.PositiveIntegerField(blank=True, null=True, verbose_name='حداکثر طول متن')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='واحد اندازه\u200cگیری')),
                ('is_required', models.BooleanField(default=False, verbose_name='اجباری')),
                ('is_filterable', models.BooleanField(default=False, verbose_name='قابل فیلتر در سایت')),
                ('is_visible', models.BooleanField(default=True, verbose_name='نمایش در صفحه محصول')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'ویژگی محصول',
                'verbose_name_plural': 'ویژگی\u200cهای محصولات',
                'ordering': ['group__sort_order', 'sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='AttributeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='اسلاگ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'گروه ویژگی',
                'verbose_name_plural': 'گروه\u200cهای ویژگی',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='اسلاگ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('description', models.TextField(blank=True, help_text='توضیحات کامل برند، تاریخچه، و اطلاعات دیگر', verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, help_text='لوگوی برند با پس زمینه شفاف (PNG)', null=True, upload_to=apps.product.models.brand.brand_image_path, verbose_name='لوگوی برند')),
                ('website', models.URLField(blank=True, help_text='آدرس وب\u200cسایت رسمی برند', verbose_name='وب\u200cسایت')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برندها',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='اسلاگ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('description', models.TextField(help_text='توضیحات کامل محصول، ویژگی\u200cها و مشخصات فنی', verbose_name='توضیحات')),
                ('price', models.DecimalField(decimal_places=0, help_text='قیمت پایه هر واحد محصول', max_digits=12, verbose_name='قیمت واحد (تومان)')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=0, help_text='قیمت تخفیف\u200cخورده (اختیاری)', max_digits=12, null=True, verbose_name='قیمت ویژه')),
                ('stock_quantity', models.PositiveIntegerField(default=0, help_text='تعداد موجود در انبار', verbose_name='موجودی')),
                ('min_quantity', models.PositiveIntegerField(default=1, help_text='کمترین تعداد قابل خرید در فروش خرده', verbose_name='حداقل تعداد خرید')),
                ('max_quantity', models.PositiveIntegerField(default=100, help_text='بیشترین تعداد قابل خرید در فروش خرده', verbose_name='حداکثر تعداد خرید')),
                ('is_wholesale_enabled', models.BooleanField(default=False, help_text='اگر فعال باشد، امکان خرید عمده وجود دارد', verbose_name='فروش عمده فعال')),
                ('wholesale_min_quantity', models.PositiveIntegerField(default=10, help_text='کمترین تعداد برای خرید عمده', verbose_name='حداقل تعداد برای عمده')),
                ('wholesale_discount_percent', models.PositiveIntegerField(default=0, help_text='درصد تخفیف برای خرید عمده (اختیاری)', verbose_name='درصد تخفیف عمده')),
                ('is_packaged', models.BooleanField(default=False, help_text='اگر فعال باشد، محصول به صورت بسته\u200cای فروخته می\u200cشود', verbose_name='محصول بسته\u200cبندی شده')),
                ('items_per_package', models.PositiveIntegerField(default=1, help_text='تعداد آیتم در هر بسته (اگر بسته\u200cبندی شده باشد)', verbose_name='تعداد در هر بسته')),
                ('weight_grams', models.PositiveIntegerField(blank=True, help_text='وزن محصول به گرم', null=True, verbose_name='وزن (گرم)')),
                ('dimensions', models.CharField(blank=True, help_text='ابعاد محصول (طول × عرض × ارتفاع) سانتیمتر', max_length=100, verbose_name='ابعاد')),
                ('main_image', models.ImageField(help_text='تصویر اصلی محصول', upload_to=apps.product.models.product.product_image_path, verbose_name='عکس شاخص')),
                ('meta_title', models.CharField(blank=True, help_text='عنوان صفحه برای SEO (اگر خالی باشد، از title استفاده می\u200cشود)', max_length=255, verbose_name='متا تایتل')),
                ('meta_description', models.TextField(blank=True, help_text='توضیحات صفحه برای SEO', verbose_name='متا دسکریپشن')),
                ('brand', models.ForeignKey(blank=True, help_text='برند محصول (اختیاری)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.brand', verbose_name='برند')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='اسلاگ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('title', models.CharField(blank=True, help_text='عنوان اختیاری برای تصویر', max_length=200, verbose_name='عنوان تصویر')),
                ('image', models.ImageField(help_text='حداکثر سایز: 5MB، فرمت\u200cهای مجاز: JPG, PNG, WEBP', upload_to=apps.product.models.gallery.gallery_image_path, verbose_name='تصویر')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='تصاویر بر اساس این عدد مرتب می\u200cشوند (اعداد کوچکتر اول)', verbose_name='ترتیب نمایش')),
                ('is_main', models.BooleanField(default=False, help_text='اگر فعال باشد، این تصویر به عنوان تصویر شاخص محصول نمایش داده می\u200cشود', verbose_name='تصویر اصلی')),
                ('product', models.ForeignKey(help_text='محصولی که این تصویر متعلق به آن است', on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تصویر گالری',
                'verbose_name_plural': 'تصاویر گالری',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='اسلاگ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('description', models.TextField(blank=True, help_text='توضیحات کامل دسته\u200cبندی', verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, help_text='تصویر شاخص دسته\u200cبندی', null=True, upload_to=apps.product.models.category.category_image_path, verbose_name='عکس دسته\u200cبندی')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='برای مرتب\u200cسازی دسته\u200cبندی\u200cها در منو', verbose_name='ترتیب نمایش')),
                ('meta_title', models.CharField(blank=True, help_text='عنوان صفحه برای SEO', max_length=255, verbose_name='متا تایتل')),
                ('meta_description', models.TextField(blank=True, help_text='توضیحات صفحه برای SEO', verbose_name='متا دسکریپشن')),
                ('parent', models.ForeignKey(blank=True, help_text='اگر این دسته\u200cبندی زیرمجموعه\u200cی دسته\u200cبندی دیگری است', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.productcategory', verbose_name='دسته\u200cبندی والد')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی محصول',
                'verbose_name_plural': 'دسته\u200cبندی محصولات',
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True, null=True, verbose_name='مقدار متنی')),
                ('value_integer', models.IntegerField(blank=True, null=True, verbose_name='مقدار عددی')),
                ('value_decimal', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='مقدار اعشاری')),
                ('value_boolean', models.BooleanField(blank=True, null=True, verbose_name='مقدار منطقی')),
                ('value_date', models.DateField(blank=True, null=True, verbose_name='مقدار تاریخ')),
                ('value_datetime', models.DateTimeField(blank=True, null=True, verbose_name='مقدار تاریخ و زمان')),
                ('value_select', models.CharField(blank=True, max_length=255, null=True, verbose_name='مقدار انتخابی')),
                ('value_multi_select', models.JSONField(blank=True, null=True, verbose_name='مقادیر انتخابی چندتایی')),
                ('value_color', models.CharField(blank=True, max_length=50, null=True, verbose_name='مقدار رنگ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_values', to='product.attribute', verbose_name='ویژگی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'مقدار ویژگی محصول',
                'verbose_name_plural': 'مقادیر ویژگی\u200cهای محصولات',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(help_text='دسته\u200cبندی\u200cهای مربوط به این محصول', related_name='products', to='product.productcategory', verbose_name='دسته\u200cبندی\u200cها'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='product.attributegroup', verbose_name='گروه ویژگی'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.attribute', verbose_name='ویژگی والد'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['slug', 'is_active'], name='product_pro_slug_bad0a5_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['parent', 'is_active'], name='product_pro_parent__0a100d_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['display_order', 'is_active'], name='product_pro_display_f01a16_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productattributevalue',
            unique_together={('product', 'attribute')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug', 'is_active'], name='product_pro_slug_ec502b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price', 'is_active'], name='product_pro_price_e0e858_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at', 'is_active'], name='product_pro_created_6b1e8c_idx'),
        ),
    ]
