# Generated by Django 4.0.3 on 2026-02-04 13:16

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='اسلاگ')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('isActive', models.BooleanField(default=True, verbose_name='فعال')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brand/', verbose_name='لوگو')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برندها',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='اسلاگ')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('isActive', models.BooleanField(default=True, verbose_name='فعال')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category/', verbose_name='تصویر')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='توضیحات محصول')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن کامنت')),
                ('isActive', models.BooleanField(default=True, verbose_name='فعال')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('typeComment', models.CharField(choices=[('recommend', 'پیشنهاد می\u200cکنم'), ('not_recommend', 'پیشنهاد نمی\u200cکنم')], max_length=20, verbose_name='نوع کامنت')),
            ],
            options={
                'verbose_name': 'کامنت',
                'verbose_name_plural': 'کامنت\u200cها',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='اسلاگ')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('isActive', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'ویژگی',
                'verbose_name_plural': 'ویژگی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='FeatureValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='مقدار')),
            ],
            options={
                'verbose_name': 'مقدار ویژگی',
                'verbose_name_plural': 'مقادیر ویژگی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='اسلاگ')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('isActive', models.BooleanField(default=True, verbose_name='فعال')),
                ('mainImage', models.ImageField(upload_to='products/main/', verbose_name='تصویر اصلی')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='توضیحات محصول')),
                ('shortDescription', models.TextField(max_length=500, verbose_name='توضیح کوتاه')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=40, verbose_name='مقدار')),
            ],
            options={
                'verbose_name': 'ویژگی محصول',
                'verbose_name_plural': 'ویژگی\u200cهای محصول',
            },
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('isActive', models.BooleanField(default=True, verbose_name='فعال')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='تصویر')),
                ('altText', models.CharField(blank=True, max_length=200, null=True, verbose_name='متن جایگزین')),
            ],
            options={
                'verbose_name': 'گالری محصول',
                'verbose_name_plural': 'گالری محصولات',
                'ordering': ['createdAt'],
            },
        ),
        migrations.CreateModel(
            name='ProductSaleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeSale', models.IntegerField(choices=[(1, 'تک فروشی'), (2, 'کارتن فروشی'), (3, 'تک فروشی با محدودیت خرید')], default=1, verbose_name='نوع فروش')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت')),
                ('memberCarton', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد در کارتن')),
                ('limitedSale', models.PositiveIntegerField(blank=True, null=True, verbose_name='محدودیت خرید')),
                ('finalPrice', models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت نهایی')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ بروزرسانی')),
                ('isActive', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'نوع فروش محصول',
                'verbose_name_plural': 'انواع فروش محصولات',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '۱ ستاره'), (2, '۲ ستاره'), (3, '۳ ستاره'), (4, '۴ ستاره'), (5, '۵ ستاره')], verbose_name='امتیاز')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'امتیاز',
                'verbose_name_plural': 'امتیازها',
            },
        ),
    ]
