# Generated by Django 4.0.3 on 2025-12-09 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='اسلاگ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('content', models.TextField(help_text='متن کامل نظر کاربر', verbose_name='متن نظر')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 'خیلی بد'), (2, 'بد'), (3, 'متوسط'), (4, 'خوب'), (5, 'عالی')], default=5, help_text='امتیاز از 1 تا 5', verbose_name='امتیاز')),
                ('is_approved', models.BooleanField(default=False, help_text='آیا نظر توسط ادمین تأیید شده است؟', verbose_name='تأیید شده')),
                ('product', models.ForeignKey(help_text='محصول مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='product.product', verbose_name='محصول')),
                ('user', models.ForeignKey(help_text='کاربری که نظر داده است', on_delete=django.db.models.deletion.CASCADE, related_name='product_comments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نظر محصول',
                'verbose_name_plural': 'نظرات محصولات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='productcomment',
            index=models.Index(fields=['product', 'is_approved', 'is_active'], name='product_pro_product_da771f_idx'),
        ),
        migrations.AddIndex(
            model_name='productcomment',
            index=models.Index(fields=['user', 'is_active'], name='product_pro_user_id_e0a07b_idx'),
        ),
    ]
