# Generated by Django 4.0.3 on 2025-12-14 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_comment_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productgallery',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='productgallery',
            name='title',
        ),
    ]
