# Generated by Django 4.0.3 on 2025-12-15 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_productgallery_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsaletype',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='productsaletype',
            name='isActive',
        ),
        migrations.RemoveField(
            model_name='productsaletype',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='productsaletype',
            name='title',
        ),
        migrations.RemoveField(
            model_name='productsaletype',
            name='updatedAt',
        ),
    ]
