# Generated by Django 4.0.3 on 2025-12-15 15:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_productsaletype_createdat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsaletype',
            name='createdAt',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AddField(
            model_name='productsaletype',
            name='isActive',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AddField(
            model_name='productsaletype',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='productsaletype',
            name='updatedAt',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ بروزرسانی'),
        ),
    ]
