# Generated by Django 4.0.3 on 2025-12-17 09:14

from django.db import migrations, models


def fix_product_sale_type_final_prices(apps, schema_editor):
    """Fix finalPrice for existing ProductSaleType records"""
    ProductSaleType = apps.get_model('product', 'ProductSaleType')

    # Update all records to set finalPrice = price
    ProductSaleType.objects.all().update(finalPrice=models.F('price'))


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_description'),
    ]

    operations = [
        migrations.RunPython(fix_product_sale_type_final_prices),
    ]
