# Generated by Django 4.0.3 on 2026-05-25 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0003_typeproducttitle_product_typetitle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_old', models.PositiveIntegerField(help_text='قیمت قبل از تغییر', verbose_name='قیمت قبلی')),
                ('price_new', models.PositiveIntegerField(help_text='قیمت بعد از تغییر', verbose_name='قیمت جدید')),
                ('percent_change', models.DecimalField(blank=True, decimal_places=2, help_text='مثبت = افزایش، منفی = کاهش', max_digits=8, null=True, verbose_name='درصد تغییر')),
                ('change_type', models.CharField(blank=True, choices=[('increase', 'افزایش'), ('decrease', 'کاهش'), ('same', 'بدون تغییر')], max_length=10, null=True, verbose_name='نوع تغییر')),
                ('changed_by_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام تغییردهنده (نسخه پشتیبان)')),
                ('source', models.CharField(choices=[('manual_phone', 'تماس تلفنی'), ('manual_whatsapp', 'پیامک/واتساپ'), ('manual_excel', 'وارد کردن از اکسل'), ('wholesaler', 'عمده\u200cفروش'), ('union', 'اتحادیه'), ('website', 'سایت دیگر'), ('other', 'سایر')], default='manual_phone', max_length=20, verbose_name='منبع قیمت')),
                ('source_detail', models.CharField(blank=True, max_length=300, null=True, verbose_name='توضیحات منبع (مثلاً نام فروشگاه)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان ثبت تغییر')),
                ('is_current', models.BooleanField(default=False, help_text='آخرین قیمت ثبت شده برای این محصول و نوع فروش', verbose_name='قیمت جاری')),
                ('note', models.TextField(blank=True, help_text="هر نکته اضافه مثل 'فروشنده گفت فردا گران می\u200cشود'", null=True, verbose_name='یادداشت')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_changes', to=settings.AUTH_USER_MODEL, verbose_name='تغییردهنده')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='product.product', verbose_name='محصول')),
                ('sale_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='product.productsaletype', verbose_name='نوع فروش')),
            ],
            options={
                'verbose_name': 'تاریخچه قیمت',
                'verbose_name_plural': 'تاریخچه قیمت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='productpricehistory',
            index=models.Index(fields=['product', 'sale_type', '-created_at'], name='price_produ_product_420b33_idx'),
        ),
        migrations.AddIndex(
            model_name='productpricehistory',
            index=models.Index(fields=['created_at'], name='price_produ_created_28f334_idx'),
        ),
        migrations.AddIndex(
            model_name='productpricehistory',
            index=models.Index(fields=['is_current'], name='price_produ_is_curr_db7378_idx'),
        ),
    ]
