# Generated by Django 4.0.3 on 2026-05-25 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0003_typeproducttitle_product_typetitle'),
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpricehistory',
            name='changed_by_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نام تغییردهنده'),
        ),
        migrations.AlterField(
            model_name='productpricehistory',
            name='is_current',
            field=models.BooleanField(default=False, verbose_name='قیمت جاری'),
        ),
        migrations.AlterField(
            model_name='productpricehistory',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='یادداشت'),
        ),
        migrations.AlterField(
            model_name='productpricehistory',
            name='percent_change',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='درصد تغییر'),
        ),
        migrations.AlterField(
            model_name='productpricehistory',
            name='price_new',
            field=models.PositiveIntegerField(verbose_name='قیمت جدید'),
        ),
        migrations.AlterField(
            model_name='productpricehistory',
            name='price_old',
            field=models.PositiveIntegerField(verbose_name='قیمت قبلی'),
        ),
        migrations.AlterField(
            model_name='productpricehistory',
            name='source_detail',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='توضیحات منبع'),
        ),
        migrations.CreateModel(
            name='ProductStockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_old', models.PositiveIntegerField(verbose_name='موجودی قبلی')),
                ('stock_new', models.PositiveIntegerField(verbose_name='موجودی جدید')),
                ('saved_stock_before_disable', models.PositiveIntegerField(blank=True, help_text='هنگام غیرفعال کردن محصول، موجودی قبلی اینجا ذخیره می\u200cشود', null=True, verbose_name='موجودی ذخیره شده قبل از غیرفعال شدن')),
                ('change_type', models.CharField(choices=[('manual', 'تغییر دستی'), ('toggle_off', 'غیرفعال شدن محصول'), ('toggle_on', 'فعال شدن محصول'), ('sale', 'فروش'), ('restock', 'افزایش موجودی'), ('system', 'تغییر سیستمی')], max_length=20, verbose_name='نوع تغییر')),
                ('changed_by_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام تغییردهنده')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان ثبت تغییر')),
                ('note', models.TextField(blank=True, null=True, verbose_name='یادداشت')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_changes', to=settings.AUTH_USER_MODEL, verbose_name='تغییردهنده')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_history', to='product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تاریخچه موجودی',
                'verbose_name_plural': 'تاریخچه موجودی\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='productstockhistory',
            index=models.Index(fields=['product', '-created_at'], name='price_produ_product_08381f_idx'),
        ),
        migrations.AddIndex(
            model_name='productstockhistory',
            index=models.Index(fields=['change_type'], name='price_produ_change__17a2dc_idx'),
        ),
    ]
