# Generated by Django 4.0.3 on 2025-12-16 15:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0002_discountbasket_isamzing_alter_copon_enddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copon',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 16, 15, 34, 19, 820382, tzinfo=utc), verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='copon',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 16, 15, 34, 19, 820382, tzinfo=utc), verbose_name='تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='discountbasket',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 16, 15, 34, 19, 820882, tzinfo=utc), verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='discountbasket',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 16, 15, 34, 19, 820882, tzinfo=utc), verbose_name='تاریخ شروع'),
        ),
    ]
