# Generated by Django 4.0.3 on 2026-05-22 11:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0003_alter_copon_enddate_alter_copon_startdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copon',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 22, 11, 53, 54, 619590, tzinfo=utc), verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='copon',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 22, 11, 53, 54, 619590, tzinfo=utc), verbose_name='تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='discountbasket',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 22, 11, 53, 54, 620591, tzinfo=utc), verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='discountbasket',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 22, 11, 53, 54, 620591, tzinfo=utc), verbose_name='تاریخ شروع'),
        ),
    ]
