# Generated by Django 4.0.3 on 2026-01-06 11:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0012_alter_copon_enddate_alter_copon_startdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copon',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 6, 11, 13, 6, 52844, tzinfo=utc), verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='copon',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 6, 11, 13, 6, 52844, tzinfo=utc), verbose_name='تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='discountbasket',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 6, 11, 13, 6, 53843, tzinfo=utc), verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='discountbasket',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 6, 11, 13, 6, 53843, tzinfo=utc), verbose_name='تاریخ شروع'),
        ),
    ]
