# Generated by Django 4.0.3 on 2026-02-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PopularSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, unique=True, verbose_name='کلیدواژه')),
                ('search_count', models.PositiveIntegerField(default=1, verbose_name='تعداد جستجو')),
                ('click_count', models.PositiveIntegerField(default=0, verbose_name='تعداد کلیک')),
                ('last_searched', models.DateTimeField(auto_now=True, verbose_name='آخرین جستجو')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'جستجوی پرطرفدار',
                'verbose_name_plural': 'جستجوهای پرطرفدار',
                'ordering': ['-search_count', '-last_searched'],
            },
        ),
    ]
