# Generated by Django 4.2.28 on 2026-02-12 16:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='createAt',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت'),
        ),
    ]
