# Generated by Django 4.0.3 on 2025-12-22 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان دسته\u200cبندی')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('isActive', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی بلاگ',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای بلاگ',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان پست')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='اسلاگ')),
                ('content', models.TextField(verbose_name='محتوای پست')),
                ('excerpt', models.TextField(blank=True, verbose_name='خلاصه پست')),
                ('mainImage', models.ImageField(blank=True, null=True, upload_to='blog/posts/', verbose_name='تصویر اصلی')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='عنوان متا')),
                ('meta_description', models.TextField(blank=True, verbose_name='توضیحات متا')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('like_count', models.PositiveIntegerField(default=0, verbose_name='تعداد لایک')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('publishedAt', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('isActive', models.BooleanField(default=True, verbose_name='فعال')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.blogcategory', verbose_name='دسته\u200cبندی')),
                ('products', models.ManyToManyField(blank=True, related_name='blog_posts', to='product.product', verbose_name='محصولات مرتبط')),
            ],
            options={
                'verbose_name': 'پست بلاگ',
                'verbose_name_plural': 'پست\u200cهای بلاگ',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='محتوای کامنت')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('isActive', models.BooleanField(default=True, verbose_name='فعال')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_comments', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده کامنت')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.blogcomment', verbose_name='پاسخ به')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blogpost', verbose_name='پست')),
            ],
            options={
                'verbose_name': 'کامنت بلاگ',
                'verbose_name_plural': 'کامنت\u200cهای بلاگ',
                'ordering': ['createdAt'],
            },
        ),
    ]
