# Generated by Django 4.0.3 on 2025-12-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-registerDate'], 'verbose_name': 'سفارش', 'verbose_name_plural': 'سفارش\u200cها'},
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.PositiveIntegerField(default=0, verbose_name='تخفیف (%)'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='price',
            field=models.PositiveIntegerField(verbose_name='قیمت واحد'),
        ),
    ]
