# Generated by Django 4.0.3 on 2026-02-04 13:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameBanner', models.CharField(max_length=100, verbose_name='نام بنر')),
                ('textBanner', models.CharField(max_length=300, verbose_name='متن بنر')),
                ('altSlide', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوشتار عکس')),
                ('imageName', models.ImageField(upload_to=utils.FileUpload.upload_to)),
                ('isActive', models.BooleanField(default=False)),
                ('registerData', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ شروع')),
                ('endData', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ پایان')),
            ],
            options={
                'verbose_name': 'بنر',
                'verbose_name_plural': 'بنرها',
            },
        ),
        migrations.CreateModel(
            name='ContactPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان شماره')),
                ('phone_number', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('phone_type', models.CharField(choices=[('mobile', 'موبایل'), ('phone', 'تلفن ثابت'), ('support', 'پشتیبانی'), ('sales', 'فروش'), ('whatsapp', 'واتساپ')], default='mobile', max_length=20, verbose_name='نوع شماره')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'شماره تماس',
                'verbose_name_plural': 'شماره\u200cهای تماس',
            },
        ),
        migrations.CreateModel(
            name='SliderMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textSlider', models.CharField(max_length=100, verbose_name='متن اسلایدر')),
                ('imageName', models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='عکس اسلایدر')),
                ('altSlide', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوشتار عکس')),
                ('isActive', models.BooleanField(default=True, verbose_name='فعال')),
                ('registerData', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ شروع')),
                ('endData', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ پایان')),
                ('link', models.CharField(blank=True, max_length=300, null=True, verbose_name='لینک')),
            ],
            options={
                'verbose_name': 'اسلایدر مرکز',
                'verbose_name_plural': 'اسلایدرها مرکز ها',
            },
        ),
        migrations.CreateModel(
            name='SliderSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textSlider', models.CharField(max_length=100, verbose_name='متن اسلایدر')),
                ('imageName', models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, verbose_name='عکس اسلایدر')),
                ('altSlide', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوشتار عکس')),
                ('isActive', models.BooleanField(default=True, verbose_name='فعال')),
                ('registerData', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ شروع')),
                ('endData', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ پایان')),
                ('link', models.CharField(blank=True, max_length=300, null=True, verbose_name='لینک')),
            ],
            options={
                'verbose_name': 'اسلایدر',
                'verbose_name_plural': 'اسلایدرها',
            },
        ),
        migrations.CreateModel(
            name='SettingShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_shop', models.CharField(max_length=200, verbose_name='نام فروشگاه')),
                ('establishment_year', models.PositiveIntegerField(verbose_name='سال تأسیس')),
                ('about_shop', models.TextField(blank=True, verbose_name='درباره فروشگاه')),
                ('is_call', models.BooleanField(default=True, verbose_name='امکان تماس')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='shop/logo/', verbose_name='لوگوی فروشگاه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('emergency_phone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_for_shop', to='main.contactphone', verbose_name='شماره تماس اضطراری')),
            ],
            options={
                'verbose_name': 'تنظیمات فروشگاه',
                'verbose_name_plural': 'تنظیمات فروشگاه',
            },
        ),
    ]
