# Generated by Django 4.0.3 on 2026-05-22 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_alter_banner_imagename_alter_slidermain_imagename_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='تاریخ')),
                ('unique_visitors', models.PositiveIntegerField(default=0, verbose_name='بازدیدکنندگان یکتا')),
                ('total_visits', models.PositiveIntegerField(default=0, verbose_name='کل بازدیدها')),
                ('page_views', models.PositiveIntegerField(default=0, verbose_name='نمایش صفحات')),
            ],
            options={
                'verbose_name': 'آمار روزانه',
                'verbose_name_plural': 'آمار روزانه',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterField(
            model_name='banner',
            name='imageName',
            field=models.ImageField(upload_to=utils.FileUpload.upload_to),
        ),
        migrations.AlterField(
            model_name='slidermain',
            name='imageName',
            field=models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='عکس اسلایدر'),
        ),
        migrations.AlterField(
            model_name='slidersite',
            name='imageMobile',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, verbose_name='عکس برای موبایل'),
        ),
        migrations.AlterField(
            model_name='slidersite',
            name='imageName',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, verbose_name='عکس اسلایدر'),
        ),
        migrations.CreateModel(
            name='UniqueVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True, verbose_name='کلید جلسه')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('first_visit', models.DateTimeField(auto_now_add=True, verbose_name='اولین بازدید')),
                ('last_visit', models.DateTimeField(auto_now=True, verbose_name='آخرین بازدید')),
                ('visit_count', models.PositiveIntegerField(default=1, verbose_name='تعداد بازدیدها')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='مرورگر و دستگاه')),
                ('referer', models.URLField(blank=True, null=True, verbose_name='صفحه قبلی')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='کشور')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='شهر')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر (لاگین شده)')),
            ],
            options={
                'verbose_name': 'بازدید یکتا',
                'verbose_name_plural': 'بازدیدهای یکتا',
                'ordering': ['-first_visit'],
            },
        ),
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, verbose_name='آدرس صفحه')),
                ('path', models.CharField(max_length=500, verbose_name='مسیر صفحه')),
                ('method', models.CharField(default='GET', max_length=10, verbose_name='متد درخواست')),
                ('status_code', models.PositiveIntegerField(default=200, verbose_name='وضعیت پاسخ')),
                ('response_time', models.FloatField(blank=True, null=True, verbose_name='زمان پاسخ (میلی\u200cثانیه)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان بازدید')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_visits', to='main.uniquevisit', verbose_name='بازدید')),
            ],
            options={
                'verbose_name': 'بازدید صفحه',
                'verbose_name_plural': 'بازدیدهای صفحات',
                'ordering': ['-created_at'],
            },
        ),
    ]
