# Generated by Django 4.0.3 on 2025-12-29 08:06

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_banner_imagename_alter_slidermain_imagename_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_shop', models.CharField(max_length=200, verbose_name='نام فروشگاه')),
                ('establishment_year', models.PositiveIntegerField(verbose_name='سال تأسیس')),
                ('about_shop', models.TextField(blank=True, verbose_name='درباره فروشگاه')),
                ('is_call', models.BooleanField(default=True, verbose_name='امکان تماس')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='shop/logo/', verbose_name='لوگوی فروشگاه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'تنظیمات فروشگاه',
                'verbose_name_plural': 'تنظیمات فروشگاه',
            },
        ),
        migrations.AlterField(
            model_name='banner',
            name='imageName',
            field=models.ImageField(upload_to=utils.FileUpload.upload_to),
        ),
        migrations.AlterField(
            model_name='slidermain',
            name='imageName',
            field=models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='عکس اسلایدر'),
        ),
        migrations.AlterField(
            model_name='slidersite',
            name='imageName',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, verbose_name='عکس اسلایدر'),
        ),
    ]
