# Generated by Django 4.0.3 on 2026-05-25 12:33

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_banner_imagename_alter_slidermain_imagename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='imageName',
            field=models.ImageField(upload_to=utils.FileUpload.upload_to),
        ),
        migrations.AlterField(
            model_name='slidermain',
            name='imageName',
            field=models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='عکس اسلایدر'),
        ),
        migrations.AlterField(
            model_name='slidersite',
            name='imageMobile',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, verbose_name='عکس برای موبایل'),
        ),
        migrations.AlterField(
            model_name='slidersite',
            name='imageName',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, verbose_name='عکس اسلایدر'),
        ),
    ]
