# Generated by Django 4.0.3 on 2025-12-29 08:13

from django.db import migrations, models
import django.db.models.deletion
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_settingshop_alter_banner_imagename_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان شماره')),
                ('phone_number', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('phone_type', models.CharField(choices=[('mobile', 'موبایل'), ('phone', 'تلفن ثابت'), ('support', 'پشتیبانی'), ('sales', 'فروش'), ('whatsapp', 'واتساپ')], default='mobile', max_length=20, verbose_name='نوع شماره')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'شماره تماس',
                'verbose_name_plural': 'شماره\u200cهای تماس',
            },
        ),
        migrations.AlterField(
            model_name='banner',
            name='imageName',
            field=models.ImageField(upload_to=utils.FileUpload.upload_to),
        ),
        migrations.AlterField(
            model_name='slidermain',
            name='imageName',
            field=models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='عکس اسلایدر'),
        ),
        migrations.AlterField(
            model_name='slidersite',
            name='imageName',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, verbose_name='عکس اسلایدر'),
        ),
        migrations.AddField(
            model_name='settingshop',
            name='emergency_phone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_for_shop', to='main.contactphone', verbose_name='شماره تماس اضطراری'),
        ),
    ]
