# Generated by Django 5.2.15 on 2026-10-05 09:58

import ckeditor_uploader.fields
import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_slidersite_description_alter_banner_imagename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingshop',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='توضیحات تکمیلی فروشگاه'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='imageName',
            field=models.ImageField(upload_to=utils.FileUpload.upload_to),
        ),
        migrations.AlterField(
            model_name='slidermain',
            name='imageName',
            field=models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='عکس اسلایدر'),
        ),
        migrations.AlterField(
            model_name='slidersite',
            name='imageMobile',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, verbose_name='عکس برای موبایل'),
        ),
        migrations.AlterField(
            model_name='slidersite',
            name='imageName',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, verbose_name='عکس اسلایدر'),
        ),
    ]
